/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amodtech_yaandroidffmpegwrapper_FfmpegJNIWrapper */

#ifndef _Included_com_amodtech_yaandroidffmpegwrapper_FfmpegJNIWrapper
#define _Included_com_amodtech_yaandroidffmpegwrapper_FfmpegJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_amodtech_yaandroidffmpegwrapper_FfmpegJNIWrapper
 * Method:    ffmpegWrapper
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_amodtech_yaandroidffmpegwrapper_FfmpegJNIWrapper_ffmpegWrapper
  (JNIEnv *, jclass, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
